### ISSUE TITLE
Average sensors broken in 2022.6.x

### ISSUE THREAD

**Issue by NCC1941** [Limych/ha-average#139]
**Environment**

- Home Assistant Core release with the issue: 2022.6 thru 2022.6.2
- This custom component release with the issue: v2.2.3
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): Supervised

**Describe the bug**
 Average sensors break in various ways in HA 2022.6.x. Restarting HA seems to influence the errant readings, but does not fix it.

2022.5.x -> 2022.6:
![Average Bug 202206](https://user-images.githubusercontent.com/90672258/171681334-cfe123f2-116b-49e7-95d0-7913d29f64f9.jpg)

2022.6.0 -> 2022.6.1:
![image](https://user-images.githubusercontent.com/90672258/172017530-7713311e-7992-470f-abc8-e9230789a5fb.png)

**Configuration.yaml**
```yaml   

Add your configs here if any.

- platform: average
    name: 'Average PirateWeather Outdoor Temperature'
    duration: 01:00
    precision: 1
    entities:
      - sensor.pirateweather_temperature

- platform: average
    name: 'Outdoor Illuminance Educated Guessor - 1h Average'
    duration: 01:00
    precision: 0
    entities:
      - sensor.illuminance_climacell
      - sensor.illuminance_ktip
      - sensor.illuminance_metno
      - sensor.illuminance_pirateweather

```

**Steps to Reproduce**
 Have average sensors. Update to 2022.6.x. Observe results. Then if you restart HA, the readings often change to be broken in different ways.

**Expected behavior**
 Sensors should behave as they did before 2022.6.

**Debug log**

```text

Add your logs here.

```

**Additional context**
