### ISSUE TITLE
Unit of measurement lost when "stacking" average sensors

### ISSUE THREAD

**Issue by StefanDorschu** [Limych/ha-average#143]
**Describe the bug**

I'm using this sensor to average my temperatures. E.g. i have several sensors in my living room which are averaged to a single value. This value (sensor) is used as an input to calculate (average again) the temperature of the first floor. When i do so, the sensor of the averaged temp in the first floor has no unit of measurement.

**Configuration.yaml**

```yaml
- platform: average
  name: "Wohnzimmer - Temperatur"
  unique_id: "wohnzimmer_temperatur"
  precision: 0
  entities:
    - sensor.wohnzimmer_sensor_glastaster_flugeltur_temperatur
    - sensor.wohnzimmer_sensor_glastaster_linke_hebeschiebeanlage_temperatur
    - sensor.wohnzimmer_sensor_glastaster_eingangstur_temperatur

- platform: average
  name: "Allgemein.Wohnräume.Erdgeschoss - Temperatur"
  unique_id: "allgemein_wohnraume_erdgeschoss_temperatur"
  precision: 1
  entities:
    - sensor.flur_eingang_temperatur
    - sensor.flur_technik_temperatur
    - sensor.kuche_temperatur
    - sensor.waschkuche_temperatur
    - sensor.alte_kuche_temperatur
    - sensor.wohnzimmer_temperatur
```

**Expected behavior**

Keep the unit of measurement.
