### ISSUE TITLE
Add Interval Option

### ISSUE THREAD

**Issue by andjones132** [Limych/ha-average#153]
I did not see any other relates issues. 

**Is your feature request related to a problem? Please describe.**
 I was checking my homeassistant datatabase states table and notice a large number of entries from the average sensors. I keep 2 weeks of data in my database and according to my math, the average sensor is updating about every 30 seconds. The sensors that that are being measured only update about every 1.5 minutes on average. So it appears the average sensor is over sampling. I thought this might be the result of the underlying sensor updating at different times in cases where multiple sensors are included in the average sensor as in the example config shown below. However, this is not the case. In the screen shot below you can see that all of the average sensor are updating on the same frequency and most of these only have one underlying sensor. The only entities in my database that update more frequently are my cameras and the HA memory sensors.  

Example config for one of the average sensors:

```
- platform: average
  name: Light Sensor Lux Average'
  duration:
    minutes: 15
  precision: 1
  entities:
    - sensor.aqara_light_sensor_living_room_lux
    - sensor.aqara_light_sensor_game_room_lux
    - sensor.aqara_light_sensor_kitchen_lux
    - sensor.aqara_light_sensor_mbr_lux
```

**Describe the solution you'd like**
 Could you add an option to set the sampling interval? In my example. I only need a 15 minute average of the underlying sensors. So I would set the inteval to only update once a minute at the most.  

**Describe alternatives you've considered**
 Live with a large database

**Additional context**

![image](https://user-images.githubusercontent.com/40303400/184559021-fa056ac7-7607-45be-8ef6-088a856c8438.png)
