### ISSUE TITLE
Unavailable sensor becomes 0

### ISSUE THREAD

**Issue by ACrazyConcept** [Limych/ha-average#16]
When the input sensor has gaps (unavailable) the average returns 0 values.

**Version of the custom_component**
1.4.3

**Configuration**
```yaml

  - platform: average
    name: bathroom_humidity
    precision: 2
    duration:
      minutes: 1
    entities:
      - sensor.bathroom_humidity_average

```
![image](https://user-images.githubusercontent.com/36438756/91436087-555e4500-e85f-11ea-8174-ffc8d2560bdf.png)

![image](https://user-images.githubusercontent.com/36438756/91436136-6b6c0580-e85f-11ea-8066-f62a1827d0ac.png)
