### ISSUE TITLE
convert_temperature issue/error

### ISSUE THREAD

**Issue by kaizersoje** [Limych/ha-average#178]
**Environment**

- Home Assistant Core release with the issue: 2022.12.0
- This custom component release with the issue: 2.3.0
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): Home Assistant OS

**Describe the bug**

There is a warning in the logs in the use of `convert_temperature` in the integration.

**Configuration.yaml**
```yaml

sensor:
  - platform: average
    name: today_temp
    entities:
      - sensor.home_temp
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

2022-12-09 06:18:10.598 WARNING (MainThread) [homeassistant.helpers.frame] Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for average using this method at custom_components/average/sensor.py, line 258: temperature = convert_temperature(float(temperature), entity_unit, ha_unit)


```

**Additional context**
