### ISSUE TITLE
Problem with propagation of temperature unit when averaging a statistics helper

### ISSUE THREAD

**Issue by Gyosa3** [Limych/ha-average#185]
**Environment**

- Home Assistant Core release with the issue: 2023.2.5
- This custom component release with the issue: 2.3.0
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv): HAOS on raspberry Pi

**Describe the bug**

I have a temperature sensor for outdoors temperature. Unit is degrees Celcius as "°C" (2 symbols).
I take an average of the temperature on a 24h window and it works well.
I want to calculate the min and max temp values on the 24h window and average them as well to make them smoother.
For this I make 2 "statistics" helpers to calculate the min and max temp of the last 24h.
Then I average these helpers on a 24h window.
All sensors show up with the "°C" measurement unit except the last 2 average sensors that are produced without unit.

**Configuration.yaml**
```yaml

# initial physical sensor
mqtt:
  sensor:
    - name: "ext_temp"
      unique_id: "ext_temp"
      state_topic: MobileAlerts/022d3ad26f5e/json
      unit_of_measurement: '°C'
      value_template: "{{value_json.temperature[0]}}"

sensor:
# average sensor with good unit propagated
  - platform: average
    name: 'Average Outside Temperature'
    unique_id: "average_ext_temp"
    precision: 1
    duration:
      days: 1
    entities:
      - sensor.ext_temp

# statistics sensors with good unit propagated
  - platform: statistics
    name: 'Minimum temp over the last 24h'
    unique_id: "min_ext_temp"
    entity_id: sensor.ext_temp
    state_characteristic: value_min
    precision: 1
    max_age:
      hours: 24

  - platform: statistics
    name: 'Maximum temp over the last 24h'
    unique_id: "max_ext_temp"
    entity_id: sensor.ext_temp
    state_characteristic: value_max
    precision: 1
    max_age:
      hours: 24

# average sensors with unit not propagated correctly
  - platform: average
    name: 'Average Min Outside Temperature'
    unique_id: "average_min_ext_temp"
    precision: 1
    duration:
      days: 1
    entities:
      - sensor.minimum_temp_over_the_last_24h

  - platform: average
    name: 'Average Max Outside Temperature'
    unique_id: "average_max_ext_temp"
    precision: 1
    duration:
      days: 1
    entities:
      - sensor.maximum_temp_over_the_last_24h
```

**Steps to Reproduce**

- Take a temp sensor;
- Create a statistics helper based on this sensor
- Create an Average sensor based on the statistics helper

**Expected behavior**

The average sensor should be able to retrieve the proper unit of measurement also from a statistics helper.

**Debug log**

```text

There are no log entries related to any issue with this component

```

**Additional context**

![image](https://user-images.githubusercontent.com/51777889/221550573-0dccc79e-1238-41d4-97df-98b70534c6db.png)
On this graph you can see on the above graph that the outdoor temp, its average, and the statistics helpers are all measured in °C as expected. The below graph shows that the average sensors of the 2 statistics helpers have no unit and Lovelace displays them is a separate graph.

I have found a possible workaround by using the attributes of the average sensor of the physical measurement:
![image](https://user-images.githubusercontent.com/51777889/221551649-33174908-d715-4f20-8aed-1149c6cc93a3.png)

I would then extract these attributes in separate sensors using the custom component "attribute extractor", then average this new sensor, but I may end up with the same issue of units if the custom component acts same as the statistics helper for the unit of measurement.
