### ISSUE TITLE
Need help with adding more then just one of the sensors. Sorry waste of time got it working.

### ISSUE THREAD

**Issue by michaelcrossland1979** [Limych/ha-average#219]
Sorry I got it working forgot to ask all knowing Google the right way. Please close this out.

### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I like to some help as to what I need to do in the YAML file so that I can have more then just one, as I want to keep track of one device but over defend time periods. Because I am try to avg out the line volage over a month and one for over 1 week and one for over 3 days and one for 12 hours.
I have been able to add one to my file and get to show up and work but if I just copy and paste it belove and just change some stuff to try to get what I wanted. it throws a fit over it. I'm no HA guru by any means.

Here I will try posting that I have that did work with just the one and the one that did not work at all.

```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

#http proxies
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.17.0.0/24
    - 192.168.1.0/24


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Example configuration.yaml entry
sensor:
  - platform: average
#    name: 'Monthly Average House Voltage'
#    precision: 0
#    duration:
#      days: 30
#    entities:
#      - sensor.entertainment_center_voltage    
#  - sensor:
#  - platform: average
#    name: 'Weekly Average House Voltage'
#    precision: 0
#    duration:
#      days: 7
#    entities:
#      - sensor.entertainment_center_voltage
#  - sensor:
#    name: '3 Days Average House Voltage'
#    precision: 0
#    duration:
#      days: 3
#    entities:
#      - sensor.entertainment_center_voltage
#  - sensor:
#  - platform: average
    name: '12 hour Average House Voltage'
    precision: 0
    duration: 12:00
    entities:
      - sensor.entertainment_center_voltage
   
template:     
  - sensor:
      - name: Feels Like Back Room 1
        unique_id: 'feellike1'
        unit_of_measurement: '°F'
        state: |-
          {% set temperature = states('sensor.avg_temp') | float%}
          {% set humidity = states('sensor.temperature_and_humidity_back_bedroom_humidity') | float %}
            {{ ((-42.379 + (2.04901523*temperature) + (10.14333127*humidity) - (0.22475541*temperature*humidity) - (0.00683783*temperature**2) - (0.05481717*humidity**2) + (0.00122874*temperature**2*humidity) + (0.00085282*temperature*humidity**2) - (0.00000199*temperature**2*humidity**2))| round(1)) }}
          
  - sensor:
      - name: Feels Like Front Door
        unique_id: 'feellike3'
        unit_of_measurement: '°F'
        state: |-
          {% set temperature = states('sensor.front_door_temp') | float%}
          {% set humidity = states('sensor.temperature_and_humidity_front_door_humidity') | float %}
            {{ ((-42.379 + (2.04901523*temperature) + (10.14333127*humidity) - (0.22475541*temperature*humidity) - (0.00683783*temperature**2) - (0.05481717*humidity**2) + (0.00122874*temperature**2*humidity) + (0.00085282*temperature*humidity**2) - (0.00000199*temperature**2*humidity**2))| round(1)) }}
```

There is what i got that works but whenever I try to add more they come back as platform not give when it is given.
Any help would be great help and when I get some more money send you 20 bucks to keep up the good work.

### Describe the solution you'd like

Just need help in fixing this so I can get more then one to work.

### Describe alternatives you've considered

I done it where i just had many of the sensor heading but that just brakes everything.

### Additional context

I don't have anything to show.
