### ISSUE TITLE
Integration unable to find an existing entity

### ISSUE THREAD

**Issue by zavjah** [Limych/ha-average#224]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Within my system log I found this error:
```
This error originated from a custom integration.

Logger: custom_components.average.sensor
Source: custom_components/average/sensor.py:475
Integration: Average Sensor (documentation, issues)
First occurred: 20:44:28 (8 occurrences)
Last logged: 20:45:00

Unable to find an entity "sensor.gw1100a_v2_2_3_outdoor_temperature"
```

This relates to those sensors i set up in my configuration.yaml:
```
  - platform: average
    name: "Average Temperature Today"
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
    entities:
      - sensor.gw1100a_v2_2_3_outdoor_temperature
  - platform: average
    name: "Average Temperature 1 Day Ago"
    duration:
      days: 1
    entities:
      - sensor.gw1100a_v2_2_3_outdoor_temperature
  - platform: average
    name: "Average Temperature last 3 days"
    duration:
      days: 3
    entities:
      - sensor.gw1100a_v2_2_3_outdoor_temperature
  - platform: average
    name: "Average Temperature last 7 days"
    duration:
      days: 7
    entities:
      - sensor.gw1100a_v2_2_3_outdoor_temperature
```

The sensor used is but existing:
![image](https://github.com/Limych/ha-average/assets/37732361/1bf3ca29-9f53-4a5c-9bd1-7cb11258aa9d)

and it seems to be working:
![image](https://github.com/Limych/ha-average/assets/37732361/fa204b7e-c980-4476-b185-51066bb47661)

Why is this error occurring?

### Describe the solution you'd like

I'd like the integration to recognize the existing sensor and not report errors although - to the best of my knowledge - working

### Describe alternatives you've considered

checked the documentation and configuration.yaml. 

### Additional context

none
