### ISSUE TITLE
Get average for a specific time period over a number of days.

### ISSUE THREAD

**Issue by AceoStar** [Limych/ha-average#23]
Hello! 

I am currently using this sensor to get the average temperature at night and another for the average temperature during the day. 

I use variations of the following

```
  - platform: average
    name: 'Average Temperature During Sun'
    start: '{{ now().replace(hour=19).replace(minute=0).replace(second=0) }}'
    duration:
       hours: 20
    entities:
      - sensor.temperature_measurement
```

The problem is that this gets the average of the current day. If I read the sensor at 12:00, the values for the current day's night have not been captured, and I get a flawed average. 

Popup output
```
Start: 2021-01-05T19:00:00-05:00
End: 2021-01-05T22:46:58-05:00
```
![image](https://user-images.githubusercontent.com/23564691/103727555-871faf00-4fa9-11eb-9971-1cb83a473d97.png)

End date is currently showing the latest available time.

**Describe the solution you'd like**
I would like the ability to get the average of a sensors value between two specific times, over a range of time. For example, The average temperature between 6am and 6pm over the past week or the average temperature between 6pm and 3 am for the past 24 hours.

**Describe alternatives you've considered**

I tried to specify both hours and days in duration, hoping this would accomplish it.

```
  - platform: average
    name: 'Average Temperature During Sun'
    start: '{{ now().replace(hour=19).replace(minute=0).replace(second=0) }}'
    duration:
       hours: 20
       days: 5
    entities:
      - sensor.temperature_measurement
```

Maybe I should just skip using Duration hours in duration and manually specify ranges and use days?

```
  - platform: average
    name: 'Average Temperature During Sun'
    start: '{{ now().replace(hour=19).replace(minute=0).replace(second=0) }}'
    end: '{{ now().replace(hour=15).replace(minute=0).replace(second=0) }}'
    duration:
       days: 1
    entities:
      - sensor.temperature_measurement
```

**
**Additional context**

Really love this tool, this is a much easier way to handle averaging values than some of the alternatives!

**Comment by Limych** [comment]
The principle of specifying the `duration` parameter is uniform across multiple components in HA. It is always a single, inseparable period of time. If you and I begin to invent a new meaning for it, we will get a huge confusion in the minds of users. And this is very bad.

The only way that I see for solving your problem is to make two levels of calculation. In the first one, calculate the average value for the required period of the current day, and with the second sensor, calculate the average value of the average values for the week.
```yaml
# Example configuration.yaml entry
sensor:
  - platform: average
    name: 'Daily Average Temperature During Sun'
    start: '{{ now().replace(hour=19).replace(minute=0).replace(second=0) }}'
    duration:
       hours: 20
    entities:
      - sensor.temperature_measurement

  - platform: average
    name: 'Average Temperature During Sun'
    duration:
       days: 5
    entities:
      - sensor.daily_average_temperature_during_sun
```
