### ISSUE TITLE
Unexpected behaviour

### ISSUE THREAD

**Issue by rednasss** [Limych/ha-average#25]
Can you explain this behaviour? Currently I have this code:

```
- platform: average
  name: "Average temperature"
  end: '{{ now().replace(hour=23).replace(minute=59).replace(second=0) }}'
  duration:
    hours: 24
  entities:
    - weather.home
```
![HA](https://user-images.githubusercontent.com/3071416/105457722-90866800-5c87-11eb-9e84-6d7589014df8.png)

On the left side (where the graph shows horizontal lines) you see my old settings with this in the code:
`end: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'`
On the right side are the settings applied shown above.
Why does the behaviour change? What I would like to achieve is the average temperature at 23:59 of the previous 24 hours, the same as happens on the left side but there it was at 0:00.
