### ISSUE TITLE
Extend documentation comparing your sensor with the HA built-in filter sensor

### ISSUE THREAD

**Issue by lmagyar** [Limych/ha-average#26]
**Is your feature request related to a problem? Please describe.**

Your sensors works as required, it shows the real, correct average of a sensor during a time period. The built in HA filter sensor changes it's output only, when it's input changes, ie. filter sensor is off by 1 precision nearly all the time. Your sensor is correct.

**Describe the solution you'd like**

Add a "Compare with filter sensor:" paragraph to the documentation mentioning this.

**Describe alternatives you've considered**

--

**Additional context**

Red line: original noisy sensor
Dark orange: filter sensor
Light orange: average sensor
(History card selected these fantastic colors...)

![Filter_02](https://user-images.githubusercontent.com/5061219/105526250-6ca44000-5ce2-11eb-9995-a96405c3cdb4.jpg)

```yaml
- platform: filter
  name: "Filter sensor"
  entity_id: sensor.xxx
  filters:
    - filter: time_simple_moving_average
      window_size: "00:01"
      precision: 1

- platform: average
  name: 'Average sensor'
  entities:
    - sensor.xxx
  duration:
    minutes: 1
  precision: 1
```
