### ISSUE TITLE
Could not convert value to float

### ISSUE THREAD

**Issue by attkri** [Limych/ha-average#40]
**Versions**

* Version of the Home Assistant: core-2021.3.4, supervisor-2021.03.6, Home Assistant OS 5.12
* Version of the custom component: 1.7.2

**Configuration**

My matching sensor looks like this:

```
    luftreiniger_oben_temperature:
      friendly_name: 'Temperatur'
      unit_of_measurement: '° C'
      device_class: 'temperature'
      value_template: '{{ states.fan.luftreiniger_oben.attributes.temperature }}'
```

The AVG entry as follows:

```
- platform: average

  name: 'Temperatur Oben AVG'
  entities:
    - sensor.treppenhaus_bewegungsmelder_oben_temperature
    - sensor.buro_bewegungsmelder_temperature
    - sensor.luftreiniger_oben_temperature
```

I get the following error:

```
Logger: custom_components.average.sensor
Source: custom_components/average/sensor.py:270
Integration: average (documentation, issues)
First occurred: 0:31:27 (2468 occurrences)
Last logged: 21:01:50

Could not convert value "<state sensor.luftreiniger_oben_temperature=22.3; unit_of_measurement=° C, friendly_name=Temperatur, device_class=temperature @ 2021-03-27T20:13:27.468485+01:00>" to float
```

What's going wrong?
