### ISSUE TITLE
State count very high

### ISSUE THREAD

**Issue by miguelmartfern** [Limych/ha-average#41]
First of all, thank you and congratulations for this great contribution to HA.

I don't know if this is really a bug or I'm missing something.

I have this sensors configured:

```
- platform: rest
  name: pws_fresno_report
  json_attributes:
    - observations
  value_template: '{{ value_json["observations"][0]["obsTimeLocal"].title() }}'
  resource: !secret wunderground_fresno_url
  scan_interval: 1800

- platform: template
  sensors:
    pws_fresno_precip_total:
      value_template: '{{ states.sensor.pws_fresno_report.attributes.observations[0].metric.precipTotal }}'
      friendly_name: Lluvia Total Fresno el Viejo        
      unit_of_measurement: "L"

- platform: average
  name: irrigation_unlimited_rain_fresno_0
  entities:
    - sensor.pws_fresno_precip_total
  precision: 1
  start: '{{ now().replace(hour=0).replace(minute=30).replace(second=0) }}'
  end: '{{ now() }}'
  scan_interval: 1800

- platform: average
  name: irrigation_unlimited_rain_fresno_1
  entities:
    - sensor.pws_fresno_precip_total
  precision: 1
  start: '{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=1) }}'
  end: '{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=1) }}'
  scan_interval: 1800
```

I record the states of my sensors for 14 days:

```
recorder:
  purge_keep_days: 14
```

When I check the total count of sensor states of each sensor during the last 14 days I get the next:

* sensor.pws_fresno_report: 895
* sensor.pws_fresno_precip_total: 145
* sensor.irrigation_unlimited_rain_fresno_0: 10552
* sensor.irrigation_unlimited_rain_fresno_1: 152

I don't understad why the sensor.irrigation_unlimited_rain_fresno_0 count is so high compared with sensor.irrigation_unlimited_rain_fresno_1 if both have the same scan_interval.

Thank you.
