### ISSUE TITLE
All 'average' sensors are 'unavailable' after update.

### ISSUE THREAD

**Issue by vigilcoma** [Limych/ha-average#57]
- Home Assistant Core release with the issue: core-2021.5.1
- This custom component release with the issue: 2.0.0
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv):  Home Assistant OS 5.13 (Docker)

After update to latest 'average' integration version all average sensors stopped working. They all are 'unavailable' now.

```yaml

- platform: average
    name: 'Average Bedroom Temperature'
    entities:
      - sensor.humidifier_temperature
      - sensor.temperature_lumi_158d0001bf2eee
      - sensor.bedroom_thermostat_temperature
```
