### ISSUE TITLE
Precision not working correctly

### ISSUE THREAD

**Issue by HA-TB303** [Limych/ha-average#6]
## Version of the custom_component
c78e313 (installed via HACS)
## Configuration

```yaml
sensor:
  - platform: average
    name: 'Overloop gemiddelde lichtsterkte'
    duration:
      minutes: 15
    precision: 0
    entities:
      - sensor.0x0017880102139e87_illuminance
```

## Describe the bug
I would expect precision: 0 to display 0 decimals.

![image](https://user-images.githubusercontent.com/9609805/67763124-43e1bc00-fa47-11e9-8d64-c46a7c1ee977.png)
