### ISSUE TITLE
Not working negative number

### ISSUE THREAD

**Issue by dragonerix** [Limych/ha-average#75]
**Environment**

- Home Assistant Core release with the issue:
- This custom component release with the issue:
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv):

**Describe the bug**

**Configuration.yaml**
```yaml

  - platform: average
    name: 'Průměrný rozdíl teploty'
    precision: 2
    entities:
      - sensor.rozdil_teploty_obyvak
      - sensor.rozdil_teploty_kuchyn
      - sensor.rozdil_teploty_chodba
      - sensor.rozdil_teploty_koupelna
      - sensor.rozdil_teploty_patro
      - sensor.rozdil_teploty_loznice
      - sensor.rozdil_teploty_sklep
      - sensor.rozdil_teploty_patro_pokoj
      

```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

Add your logs here.

```

**Additional context**
