### ISSUE TITLE
'unique_id' ignored

### ISSUE THREAD

**Issue by glerak** [Limych/ha-average#76]
**Environment**

- Home Assistant Core release with the issue: core-2021.6.6
- This custom component release with the issue: 2.1.0
- Last working this custom component release (if known): ?
- Operating environment (Home Assistant/Supervisor/Docker/venv): Home Assistant Supervised

**Describe the bug**

The value in 'unique_id' is ignored.
There is entity ID "sensor.atmosfericky_tlak_prumer_za_15_min" in HA, i would like "atmosfericky_tlak_average15", as it is in 'unique_id' specified.
I tested it with and without '' ""...

**/config/configuration.yaml**
```yaml

sensor: !include sensors.yaml

```

**/config/sensors.yaml**
```yaml

-   platform: average
    name: 'Atmosférický tlak (průměr za 1 min).'
    unique_id: atmosfericky_tlak_average1
    precision: 2
    duration:
      minutes: 1
    entities:
    - sensor.temp_001_aqara_pressure
    - sensor.temp_002_aqara_pressure
    - sensor.temp_003_aqara_pressure
    - sensor.temp_004_aqara_pressure
    - sensor.temp_005_aqara_pressure
    - sensor.temp_006_aqara_pressure
    - sensor.temp_008_aqara_pressure
    - sensor.temp_009_aqara_pressure
    - sensor.temp_010_aqara_pressure

-   platform: average
    name: 'Atmosférický tlak (průměr za 15 min).'
    unique_id: atmosfericky_tlak_average15
    precision: 2
    duration:
      minutes: 15
    entities:
    - sensor.temp_001_aqara_pressure
    - sensor.temp_002_aqara_pressure
    - sensor.temp_003_aqara_pressure
    - sensor.temp_004_aqara_pressure
    - sensor.temp_005_aqara_pressure
    - sensor.temp_006_aqara_pressure
    - sensor.temp_008_aqara_pressure
    - sensor.temp_009_aqara_pressure
    - sensor.temp_010_aqara_pressure

```

**Steps to Reproduce**

**Expected behavior**

**Debug log**

```text

Add your logs here.

```

**Additional context**
