### ISSUE TITLE
Not quite ignoring null values.

### ISSUE THREAD

**Issue by skynetforcats** [Limych/ha-average#79]
**Environment**

- Home Assistant Core release with the issue: 2021.7.1
- This custom component release with the issue: 2.1.0
- Last working this custom component release (if known): N/A
- Operating environment (Home Assistant/Supervisor/Docker/venv): Docker on Debian

**Describe the bug**

The sensor does not quite ignore null values it seems. Example below.

**Configuration.yaml**
```yaml

  - platform: average
    name: motion_sensor_1_temperature_average
    precision: 4
    duration:
      minutes: 1
    entities:
      - sensor.motion_sensor_1_temperature
```
![image](https://user-images.githubusercontent.com/36438756/125508676-0b6d4709-4aca-485b-a49b-f882666e44ae.png)
![image](https://user-images.githubusercontent.com/36438756/125508715-85d9c0dc-9d2e-43c7-9cc2-3ae7d04fad8d.png)
![image](https://user-images.githubusercontent.com/36438756/125515097-3f1f1ef0-a8f1-4544-a704-fa4ef4eb479c.png)

**Steps to Reproduce**

**Expected behavior**

If the goal is to ignore null values then the result above should have been either null or the average of last known non-null values. Or maybe some other option. I don't know what the best approach is.

**Debug log**

```text

Add your logs here.

```

**Additional context**
