### ISSUE TITLE
Separate charts, one with data and one with average

### ISSUE THREAD

**Issue by barcik75** [Limych/ha-average#94]
**Environment**

- Home Assistant Core release with the issue: 2021.9.7
- This custom component release with the issue: 2.2.0
- Last working this custom component release (if known): I don't know
- Operating environment (Home Assistant/Supervisor/Docker/venv): Home Assistant OS 6.4

**Describe the bug**

I creating Avarage sensor how it is decribed in documentaion, but Avarage is on additional entity, not together with main sensor.
And also when it isn't set [Duration] I have identical values of main sensor. Look on link [https://ibb.co/1bG7VyY](https://ibb.co/1bG7VyY)

**Configuration.yaml**
```yaml

Add your configs here if any.
#Avarage
  - platform: average
    name: 'Average Flights Tracked'
    duration:
      days: 1
    entities:
      - sensor.fr24_feeder_aircraft_tracked
  - platform: average
    name: 'Average Flights Uploaded'
    entities:
      - sensor.fr24_feeder_aircraft_uploaded
  - platform: average
    name: 'Average CPU Temperature'
    entities:
      - sensor.cpu_temperature
```

**Steps to Reproduce**

**Expected behavior**

 All data on one chart

**Debug log**

```text

Add your logs here.

```

**Additional context**
