### ISSUE TITLE
Avoid that unavailable and unknown values are used to make average.

### ISSUE THREAD

**Issue by Melkor82** [Limych/ha-average#99]
**Environment**

- Home Assistant Core release with the issue:
- This custom component release with the issue:
- Last working this custom component release (if known):
- Operating environment (Home Assistant/Supervisor/Docker/venv):

**Describe the bug**
  I use the average sensor to calculate average temperature in the house. I am using 6 zigbee sensor. If the battery of one gets 
 low it disconnects and it reports unavailable or unknown as state. I can notice this as the average value drops because i think 
 that the value is used to make the average is 0.

**Configuration.yaml**
```yaml

Add your configs here if any.

```

**Steps to Reproduce**
 Just make one sensor states to report "unavailable" or "unknown"

**Expected behavior**

  Ignore "unavailable" and "unknown" states of the sensors

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by xstrex** [comment]
Came here to report this; I now have millions of logs from this component because it can't find the average for an unknown or unavailable entity id.

**Comment by TTLucian** [comment]
Hi. Even though in the documentation is stated that: "By default, undefined values are not included in the average calculation" upon HA core restart i get low and zero values:
![image](https://user-images.githubusercontent.com/1855276/146881026-705ff659-003e-45b6-aafd-6351d449eec1.png)

I believe this happens because the availability of the sensors. It also causes issues with other entities that use the average sensor as input:
![image](https://user-images.githubusercontent.com/1855276/146878448-4d2fed2a-8838-4648-97a8-7004e8887b0c.png)

**Comment by drogfild** [comment]
For me it seems that this started when I updated HA from 2021.12.2 to 2021.12.8. At least for me this hasn't happened before that upgrade. Upgraded Average to 2.2.1 didn't help.

![image](https://user-images.githubusercontent.com/35920772/148643309-76c9c85a-1a89-49d7-8ffd-44154080940f.png)

```
  - platform: average
    name: 'Average Temperature House'
    unique_id: __legacy__
    duration:
      minutes: 30
    entities:
      - sensor.kitchen_ble_temperature
      - sensor.guestroom_ble_temperature
      - sensor.livingroom_ble_temperature
      - sensor.xiaomi_temp_childrensroom_temperature
```

As you can see from the picture all entities are between 20.9 and 22.6, and still average is 16.26. One of those sensors is offline since 10:10. But that big drop happened at 11:05. 

I would assume that one sensor would be ruled out as it has happened before. Could you please check into this?

Edit:
Added second average to verify my findings. Second average is with same setup but without livingroom_ble_temperature sensor. All other details are same, except this one calculates average without that one failed sensor. This one calculates average correctly. So ruling out bad sensors doesn't work as it supposed to.
![image](https://user-images.githubusercontent.com/35920772/148643988-9ac4eee2-caac-4d74-af17-dac13ab80d90.png)

**Comment by drogfild** [comment]
Any update on this one? I'm currently using built-in mean calculation instead of this, because it can handle missing values just fine. But it obviously isn't as versatile as this. And it doesn't calculate average during some time period. That's why I would like to use this component instead.

**Comment by lmagyar** [comment]
I think the restart related part of this issue is related to #98. Though I wasn't able to figure out the root cause.

**Comment by paolo-ermit** [comment]
I'm having the same problem.
When a sensor becomes unavailable, the average value is wrong, considering the value as 0 instead of ignoring it

**Comment by xarly** [comment]
Same here, I see problem still open

**Comment by Melkor82** [comment]
I switched to the native HA average sensor in the helpers page. It is behaving as supposed

**Comment by lmagyar** [comment]
Though the built-in HA integrations behave differently, eg. they go unavailable immediately after the sensor goes unavailable (eg. WiFi outage), and generic_thermostat will not change state on unavailable temperature.

In my case I've added a wrapper sensor to get a default value for the thermostat, and I use the built-in filter (average) integration sensor to draw graphs (without the jumps to the default temperature). See: https://community.home-assistant.io/t/average-sensor/111674/154

**Comment by JoryHogeveen** [comment]
Same issue here, an undefined value drops the average.

**Comment by maia** [comment]
The issue still exists. For unavailable sensors a value of zero will be used to calculate the average:
```
  - platform: average
    name: "Outdoor temperature"
    unique_id: "outdoor_temperature"
    entities:
      - sensor.terrasse_eve_weather_temperature
      - sensor.terrasse_inkbird_temperature
      - sensor.openweathermap_temperature
    duration:
      minutes: 5
    precision: 2
```
See how the blue line (average) drops each time the purple line (Homekit/Thread sensor from Eve) is unavailable:
<img width="1162" alt="Bildschirmfoto 2023-11-28 um 16 22 28" src="https://github.com/Limych/ha-average/assets/9836/c694d57f-983a-401e-9b3a-71f6d358e058">
